Write some test

diff --git a/secret b/secret
--- a/secret
+++ b/secret
@@ -9,34 +9,57 @@ whoami=`whoami`
 machine=`uname -n`
 time=`date`
 
+if ! [ -x "$(command -v jq)" ]; then
+  echo 'Error: jq is not installed.' >&2
+  exit 1
+fi
+
 read() {
-    aws secretsmanager get-secret-value --secret-id $1 --version-stage AWSCURRENT | grep SecretString | awk '{print substr($2, 1, length($2)-1)}' | awk '{print substr($1, 2, length($1)-2)}'
+    if [ $# != 1 ]; then
+        echo "[USAGE]:: secret readjson /production/team-1/cluster-1"
+        exit 1
+    fi
+    aws secretsmanager get-secret-value --secret-id $1 --version-stage AWSCURRENT | jq -r .SecretString
     RETVAL=$?
     exit $RETVAL
 }
 
 write() {
+    if [ $# != 2 ]; then
+        echo "[USAGE]:: secret write /production/team-1/cluster-1 supers3cretstirng"
+        exit 1
+    fi
     aws secretsmanager create-secret --name $1 --description "Created by $whoami using $machine on $time" --secret-string $2
     RETVAL=$?
     exit $RETVAL
 }
 
 update() {
+    if [ $# != 2 ]; then
+        echo "[USAGE]:: secret update /production/team-1/cluster-1 supers3cretstirng"
+        exit 1
+    fi
     aws secretsmanager update-secret --secret-id $1 --secret-string $2
+    RETVAL=$?
+    exit $RETVAL
 }
 
 ensure() {
+    if [ $# != 2 ]; then
+        echo "[USAGE]:: secret ensure /production/team-1/cluster-1"
+        exit 1
+    fi
     aws secretsmanager describe-secret --secret-id $1
     if [ "$?" -eq "0" ]; then
         echo "$1 exists."
         RETVAL=0
     fi
     exit $RETVAL
+
 }
 
-
 case "$1" in
-    read|get|r)
+    read|r)
         read $SECRETKEY
         ;;
     write|w)
@@ -49,8 +72,7 @@ case "$1" in
         ensure $SECRETKEY
         ;;
     *)
-        echo "Usage: {read|write|ensure|update}"
+        echo "Usage: {readjson|read|write|ensure|update}"
         exit 1
-        ;;
 esac
 exit $RETVAL
